version: '3'

services:
  db:
    image: postgres
  web:
    image: yiliao/compose-django:v1
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8080"]
    ports:
      - "8080:8080"
    depends_on:
      - db
